# CryptoCurrency Analysis

## Importing Bitcoin Data

In [9]:
import pandas as pd
from datetime import datetime

In [10]:
dateparse = lambda dates: pd.datetime.strptime(dates, '%d-%m-%Y')
btc=pd.read_csv('Dataset/Bitcoin.csv',parse_dates=['Date'],index_col='Date', date_parser=dateparse)
btc = btc.iloc[::-1]
btc.tail(5)

<ipython-input-10-4d72362c0878>:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  dateparse = lambda dates: pd.datetime.strptime(dates, '%d-%m-%Y')

,Open,High,Low,Close,Volume,Market Cap
Date,,,,,,
2021-06-23,32515.714303,34753.408503,31772.632355,33723.028978,4.631711e+10,6.320113e+11
2021-06-24,33682.800404,35228.852611,32385.214696,34662.435894,3.312337e+10,6.496440e+11
2021-06-25,34659.104499,35487.248003,31350.883858,31637.780055,4.023090e+10,5.929782e+11
2021-06-26,31594.663571,32637.587193,30184.501794,32186.277671,3.858539e+10,6.032760e+11
2021-06-27,32287.523211,34656.127356,32071.757148,34649.644588,3.551164e+10,6.494617e+11

In [5]:
maxValue=btc[btc['Close']==max(btc.Close)]
print("Highiest value of bitcoin")
maxValue

Highiest value of bitcoin

,Open,High,Low,Close,Volume,Market Cap
Date,,,,,,
2021-04-13,59890.01779,63742.283337,59869.956293,63503.45793,6.998345e+10,1.186364e+12

In [7]:
btc.describe()

,Open,High,Low,Close,Volume,Market Cap
count,2983.000000,2983.000000,2983.000000,2983.000000,2.983000e+03,2.983000e+03
mean,6613.843852,6805.260516,6402.037782,6625.160672,1.084006e+10,1.192478e+11
std,11199.197921,11553.544329,10781.352553,11209.848478,1.887826e+10,2.092413e+11
min,68.504997,74.561096,65.526001,68.431000,0.000000e+00,7.784112e+08
25%,429.792999,435.968491,421.852005,429.862000,3.013725e+07,6.294347e+09
50%,2191.560059,2303.899902,2071.989990,2202.419922,9.174120e+08,3.601766e+10
75%,8494.818022,8687.633944,8230.187652,8500.334961,1.575577e+10,1.488823e+11
max,63523.754869,64863.098908,62208.964366,63503.457930,3.509679e+11,1.186364e+12

In [8]:
btc.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2983 entries, 2013-04-28 to 2021-06-27
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Open        2983 non-null   float64
 1   High        2983 non-null   float64
 2   Low         2983 non-null   float64
 3   Close       2983 non-null   float64
 4   Volume      2983 non-null   float64
 5   Market Cap  2983 non-null   float64
dtypes: float64(6)
memory usage: 163.1 KB

## Importing DogeCoin Data

In [12]:
doge=pd.read_csv('Dataset/Meme Coin/Dogecoin.csv',parse_dates=['Date'],index_col='Date', date_parser=dateparse)
doge = doge.iloc[::-1]
doge.tail(5)

<ipython-input-10-4d72362c0878>:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  dateparse = lambda dates: pd.datetime.strptime(dates, '%d-%m-%Y')

                Open      High       Low     Close        Volume    Market Cap
Date
2021-06-23  0.190671  0.247110  0.180979  0.232174  5.098675e+09  3.021735e+10
2021-06-24  0.234970  0.268690  0.222527  0.262782  3.844648e+09  3.420559e+10
2021-06-25  0.263480  0.289145  0.230006  0.239153  5.542163e+09  3.113117e+10
2021-06-26  0.237673  0.255127  0.230972  0.244784  2.649457e+09  3.186753e+10
2021-06-27  0.246045  0.266891  0.240894  0.264450  2.167522e+09  3.443160e+10

In [14]:
maxValue=doge[doge['Close']==max(doge.Close)]
print("Highiest value of Dogecoin")
maxValue

Highiest value of Dogecoin

               Open      High       Low     Close        Volume    Market Cap
Date
2021-05-07  0.58111  0.731972  0.520174  0.684777  2.861508e+10  8.868082e+10

In [17]:
doge.describe()

,Open,High,Low,Close,Volume,Market Cap
count,2752.000000,2752.000000,2752.000000,2752.000000,2.752000e+03,2.752000e+03
mean,0.012891,0.014171,0.011652,0.012995,4.286633e+08,1.660441e+09
std,0.060946,0.067809,0.054061,0.061207,2.810452e+09,7.937786e+09
min,0.000087,0.000089,0.000085,0.000087,0.000000e+00,1.509085e+06
25%,0.000226,0.000231,0.000222,0.000226,2.525640e+05,2.336210e+07
50%,0.001824,0.001909,0.001750,0.001824,5.405195e+06,2.113453e+08
75%,0.002882,0.002965,0.002785,0.002881,5.016303e+07,3.472437e+08
max,0.687801,0.737567,0.608168,0.684777,6.941068e+10,8.868082e+10