In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
 
df = pd.read_csv('Dataset/wine.csv')
df

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
x=df.iloc[:,1:13]
y=df.iloc[:,0]
x

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6487 non-null   float64
 1   volatile acidity      6489 non-null   float64
 2   citric acid           6494 non-null   float64
 3   residual sugar        6495 non-null   float64
 4   chlorides             6495 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6488 non-null   float64
 9   sulphates             6493 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 609.2 KB

In [5]:
from sklearn.impute import SimpleImputer
# First create an Imputer , Stratergy means what we want to write in place of missed value
mss = SimpleImputer (missing_values = np.nan, strategy = 'mean')  
 
# Set which columns imputer should perform
mss = mss.fit (x.iloc[:,[0,1,2,3,4,8,9]])
# update values of X with new values
x.iloc[:,[0,1,2,3,4,8,9]] = mss.transform(x.iloc[:,[0,1,2,3,4,8,9]])

print(x)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045
1               6.3             0.300         0.34             1.6      0.049
2               8.1             0.280         0.40             6.9      0.050
3               7.2             0.230         0.32             8.5      0.058
4               7.2             0.230         0.32             8.5      0.058
...             ...               ...          ...             ...        ...
6492            6.2             0.600         0.08             2.0      0.090
6493            5.9             0.550         0.10             2.2      0.062
6494            6.3             0.510         0.13             2.3      0.076
6495            5.9             0.645         0.12             2.0      0.075
6496            6.0             0.310         0.47             3.6      0.067

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00   0.450000
1                    14.0                 132.0  0.99400  3.30   0.490000
2                    30.0                  97.0  0.99510  3.26   0.440000
3                    47.0                 186.0  0.99560  3.19   0.400000
4                    47.0                 186.0  0.99560  3.19   0.400000
...                   ...                   ...      ...   ...        ...
6492                 32.0                  44.0  0.99490  3.45   0.580000
6493                 39.0                  51.0  0.99512  3.52   0.531215
6494                 29.0                  40.0  0.99574  3.42   0.750000
6495                 32.0                  44.0  0.99547  3.57   0.710000
6496                 18.0                  42.0  0.99549  3.39   0.660000

      alcohol  quality
0         8.8        6
1         9.5        6
2        10.1        6
3         9.9        6
4         9.9        6
...       ...      ...
6492     10.5        5
6493     11.2        6
6494     11.0        6
6495     10.2        5
6496     11.0        6

[6497 rows x 12 columns]

In [6]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 609.2 KB

In [8]:
from sklearn.preprocessing import LabelEncoder
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[1 1 1 ... 0 0 0]

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

print(x_train)
print(x_test)
print(y_train)
print(y_test)

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
5372           10.5             0.280         0.51             1.7      0.080
1790            9.4             0.160         0.30             1.4      0.042
5879            9.5             0.860         0.26             1.9      0.079
1065            8.3             0.220         0.38            14.8      0.054
852             6.9             0.180         0.36             1.3      0.036
...             ...               ...          ...             ...        ...
4931            6.9             0.605         0.12            10.7      0.073
3264            5.9             0.240         0.12             1.4      0.035
1653            7.9             0.330         0.28            31.6      0.053
2607            8.9             0.260         0.33             8.1      0.024
2732            7.9             0.510         0.34             2.6      0.049

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
5372                 10.0                  24.0  0.99820  3.20       0.89
1790                 26.0                 176.0  0.99540  3.15       0.46
5879                 13.0                  28.0  0.99712  3.25       0.62
1065                 32.0                 126.0  1.00020  3.22       0.50
852                  40.0                 117.0  0.99340  3.27       0.95
...                   ...                   ...      ...   ...        ...
4931                 40.0                  83.0  0.99930  3.45       0.52
3264                 60.0                 247.0  0.99358  3.34       0.44
1653                 35.0                 176.0  1.01030  3.15       0.38
2607                 47.0                 202.0  0.99558  3.13       0.46
2732                 13.0                 135.0  0.99335  3.09       0.51

      alcohol  quality
5372      9.4        6
1790      9.1        5
5879     10.0        5
1065      9.7        5
852       9.5        7
...       ...      ...
4931      9.4        6
3264      9.6        6
1653      8.8        6
2607     10.8        6
2732     10.0        5

[5197 rows x 12 columns]
      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
5316           11.9              0.38         0.51             2.0      0.121
5210            9.0              0.46         0.31             2.8      0.093
3518            7.5              0.20         0.41             1.2      0.050
1622            6.5              0.44         0.49             7.7      0.045
2443            6.6              0.32         0.33             2.5      0.052
...             ...               ...          ...             ...        ...
5710           10.8              0.45         0.33             2.5      0.099
6475            6.2              0.70         0.15             5.1      0.076
1433            7.1              0.29         0.49             1.2      0.031
2707            6.5              0.23         0.36            16.3      0.038
2887            6.4              0.20         0.28             2.5      0.032

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
5316                  7.0                  20.0  0.99960  3.24       0.76
5210                 19.0                  98.0  0.99815  3.32       0.63
3518                 26.0                 131.0  0.99133  3.19       0.52
1622                 16.0                 169.0  0.99570  3.11       0.37
2443                 40.0                 219.5  0.99316  3.15       0.60
...                   ...                   ...      ...   ...        ...
5710                 20.0                  38.0  0.99818  3.24       0.71
6475                 13.0                  27.0  0.99622  3.54       0.60
1433                 32.0                  99.0  0.98930  3.07       0.33
2707                 43.0                 133.0  0.99924  3.26       0.41
2887                 24.0                  84.0  0.99168  3.31       0.55

      alcohol  quality
5316     10.4        6
5210      9.5        6
3518     11.1        5
1622      8.7        6
2443     10.0        5
...       ...      ...
5710     10.8        5
6475     11.9        6
1433     12.2        6
2707      8.8        5
2887     11.5        5

[1300 rows x 12 columns]
[0 1 0 ... 1 1 1]
[0 0 1 ... 1 1 1]

In [11]:
from sklearn.ensemble import RandomForestClassifier
RFclassifier = RandomForestClassifier(n_estimators=10, random_state=42, criterion = 'entropy')


RFclassifier.fit(x_train,y_train) # training



prediction = RFclassifier.predict(x_test)# testing 


print(prediction)

[0 0 1 ... 1 1 1]

In [12]:

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, prediction))

0.9938461538461538